import { describe, expect, it } from "vitest";
import { metadata } from "./layout";

describe("RootLayout", () => {
  it("has correct metadata", () => {
    expect(metadata).toEqual({
      title: "Create Next App",
      description: "Generated by create next app",
    });
  });

  it("exports a default function", async () => {
    // This test verifies that the layout exports a default function
    // We can't easily test the actual rendering without React Testing Library
    const layoutModule = await import("./layout");
    expect(typeof layoutModule.default).toBe("function");
  });
});
